### ISSUE TITLE
Composer v2.0 issue

### ISSUE THREAD

**Issue by hracik** [ddeboer/vatin-bundle#18]
Deprecation Notice: Class Ddeboer\VatinBundle\Tests\Validator\Constraints\ValidatorTest located in ./vendor/ddeboer/vatin-bundle/Tests/Validator/Contraints/ValidatorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php

**Comment by ddeboer** [comment]
Thanks for the report @hracik. When exactly do you get this notice?

**Comment by ddeboer** [comment]
Released as 2.2.1.
