### ISSUE TITLE
Compatibility with Symfony 6

### ISSUE THREAD

**Issue by adrienlamotte** [ddeboer/vatin-bundle#22]
Hello ! 

Could you make it compatible with Symfony 6 please ?

Thank you!

**Comment by jukuan** [comment]
+1

**Comment by jukuan** [comment]
Here is my Pull Request: https://github.com/ddeboer/vatin-bundle/pull/24/files with simple change. 
I've tested it locally, it works with Symfony 6.

**Comment by ddeboer** [comment]
Thanks @jakuan! This bundle now supports Symfony 6.
