### ISSUE TITLE
Uncaught ViesException using checkExistence=true

### ISSUE THREAD

**Issue by PaddyLock** [ddeboer/vatin-bundle#5]
If I use the validation with checkExistence=true

```
@Vatin(checkExistence=true)
```

I am getting the following error:

Error communicating with VIES service
500 Internal Server Error - ViesException
1 linked Exception: SoapFault »

ViesException: Error communicating with VIES service
SoapFault: SERVER_BUSY

Can this Exception be caught?

Thanks

**Comment by PaddyLock** [comment]
I thought this was a temporary glitch but it seems that I always get this error when I use checkExistence=true

    CRITICAL - Uncaught PHP Exception Ddeboer\Vatin\Exception\ViesException: "Error communicating with VIES service" at /Users/patricklock/Sites/Helios/vendor/ddeboer/vatin/src/Ddeboer/Vatin/Vies/Client.php line 67

**Comment by ddeboer** [comment]
Have you verified that the API is up? Perhaps try with the VATIN library?

**Comment by PaddyLock** [comment]
How do I verify the API is up? do you mean VIES? Not sure what you mean "try with VATIN library" ?

**Comment by ddeboer** [comment]
Yes, the VIES API. You can directly interact with it using https://github.com/ddeboer/vatin.

**Comment by PaddyLock** [comment]
Yes it woks fine if I use the VATIN validator directly. I have made a custom validator instead.

thanks

**Comment by ddeboer** [comment]
This is probably due to the VIES service, which is unreliable, being down at the moment of validation. Should we swallow the exception and just consider the VAT valid if the service is down?

**Comment by ddeboer** [comment]
Now converting into a ValidatorException; see https://github.com/ddeboer/vatin-bundle#validate-number-existence.
