### ISSUE TITLE
vatin-bundle is not checking the existence 

### ISSUE THREAD

**Issue by phpdeveloper1** [ddeboer/vatin-bundle#6]

**Comment by sstok** [comment]
Are your Forms using a different validation group or something?

Ps. Please use the correct Markdown syntax for code block as makes reading much easier 👍 
https://guides.github.com/features/mastering-markdown/

**Comment by phpdeveloper1** [comment]
This is my twig. 
 <label>{% trans %}VAT Number{% endtrans %}</label>
                                {{ form_widget(artistForm.vatNumber, {'attr': {'placeholder': 'VAT number', 'class': 'setField toEdit inputOther'}}) }}
                                {% if errors['vatNumber'] is defined %}
                                    <div class="inputError fieldError vatNumberError">
                                        <p>{{ errors['vatNumber'] }}</p>
                                    </div>
                                {% endif %}
                                    <div class="inputError fieldError vatNumberError">
                                        <p>{{ errors['vatNumber'] }}</p>
                                    </div>
                                {% endif %}

And if the field is empty it will display the message"VAT number is required" since I have used this :

@Assert\NotBlank(groups={"edit","vatNumber"}, message="VAT Number is required")

**Comment by phpdeveloper1** [comment]
No errors are displayed
