### ISSUE TITLE
Regarding configuration

### ISSUE THREAD

**Issue by phpdeveloper1** [ddeboer/vatin-bundle#8]
Do I need to configure the bundle in config.yml  via the config:dump-reference?

**Comment by sstok** [comment]
No, enabling the bundle should be enough to get it working.

**Comment by ddeboer** [comment]
Exactly. As of now this bundle has no configuration, because it needs none. :wink:

**Comment by phpdeveloper1** [comment]
My model is as follows:

use Ddeboer\VatinBundle\Validator\Constraints;
/**
 * @ORM\Table(name="artist")
 * @ORM\Entity(repositoryClass="MainBundle\Repository\ArtistRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Artist
{ 
/**
     * @ORM\Column(name="vat_number", type="string", nullable=true)
     * @Assert\NotNull(groups={"edit", "vat_number"},message="VAT Number is required")
     * @Assert\NotBlank(groups={"edit", "vat_number"},message="VAT Number is required")
     * @Vatin(checkExistence=true)
     */
    protected $vatNumber;
}

--------------------------------------------------
view.html.twig is as folows
<div class="row show-only-company">
                                <label>{% trans %}VAT Number{% endtrans %}</label>
                                {{ form_widget(artistForm.vatNumber, {'attr': {'placeholder': 'VAT number', 'class': 'setField toEdit inputOther'}}) }}
                                {% if errors['vatNumber'] is defined %}
                                    <div class="inputError fieldError vatNumberError">
                                        <p>{{ errors['vatNumber'] }}</p>
                                    </div>
                                {% endif %}
                            </div>
------------------------------------------------------
composer.json is "ddeboer/vatin-bundle": "^2.0"

Also appkernel.php is modified with new Ddeboer\VatinBundle\DdeboerVatinBundle() in registerBundles()

---------------------------------------------------
These are the only changes that I made .Did I miss anything?It would be really helpful if you can provide a sample project with a text box field that does VAT validation so that I can check with mine to see if there is some mistakes

**Comment by ddeboer** [comment]
You have a small `v` where you need a capital `V`:

```
use Ddeboer\VatinBundle\Validator\Constraints\Vatin;
```

instead of:

```
use Ddeboer\VatinBundle\Validator\Constraints\vatin;
```

There’s an example in the [docs](https://github.com/ddeboer/vatin-bundle#validate-number-format) and one on the [functional tests](https://github.com/ddeboer/vatin-bundle/blob/master/Tests/Functional/Model.php).

**Comment by phpdeveloper1** [comment]
I tried that one for debug purpose to see if it shows some errors.Sorry I forgot to change it back to Vatin while sending you. It didn't work.But if I use it directly as a service in my controller it is working. Eg:If I use this in my controller it works:
      $vies = $this->get('ddeboer_vatin.vies.client');
       $checkVatResponse = $vies->checkVat('NL', '811018349B01');
       var_dump($checkVatResponse);
       But issue is only with @Vatin annotation.
       The other annotation with @assert is working and displays the error message "vat number is required"as well.
I also tried App/console doctrine:schema:update —dump-sql and also —force to see whether it makes any change.But no changes if i remove or add @Vatin

**Comment by ddeboer** [comment]
What happens if you try to validate an *invalid* VAT number? Do you get a validation error?

**Comment by phpdeveloper1** [comment]
yes if i use it as a service in controller as shown in example.But not if i use @Vatin

**Comment by ddeboer** [comment]
I also see that you’re using [validation groups](https://symfony.com/doc/current/validation/groups.html):

```
@Assert\NotNull(groups={"edit", "vat_number"},message="VAT Number is required")
```

versus

```
@Vatin(checkExistence=true)
```

So I’m guessing you’re validating using the `edit` and/or the `vat_number` group. Try to add `groups={"edit", "vat_number"}` to the `@Vatin` annotation.

**Comment by phpdeveloper1** [comment]
Thank you very much .It worked.:)

**Comment by ddeboer** [comment]
Awesome!
